project_id = "xdixdqyzjfdqummwpuzg"

[functions.send-invitation]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.analyze-ingredients]
verify_jwt = false
